title: <p align="center"> Sagarika t</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sagarika-tamvada-163467114/">LinkedIn</a> |
  <a href="https://github.com/sagarikat-26">GitHub</a>
  
  <br>   
  I'm an aspiring Machine Learning engineer.
  Currently employed at HP Inc as a cloud developer 
  and also pursuing masters from IIIT-B in Artificial Intelligence
  & Machine Learning
  <br>
  </p>



theme: jekyll-theme-minimal
